name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Build Docker image
      run: |
        docker build -t dpentim78/simple-web-app:${{ github.sha }} .

    - name: Log in to Docker Hub
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      env:
        DOCKER_USERNAME: dpentim78
        DOCKER_PASSWORD: Jumamudo84

    - name: Check values.yaml before sed
      run: cat helm/simple-web-app/values.yaml

    - name: Update Helm chart image tag
      run: |
        sed -i 's|image: dpentim78/simple-web-app:.*|image: dpentim78/simple-web-app:${{ github.sha }}|' helm/simple-web-app/values.yaml

    - name: Check values.yaml after sed
      run: cat helm/simple-web-app/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add helm/simple-web-app/values.yaml
        git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
        git push

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy with ArgoCD
      run: |
        helm version
        argocd login $ARGOCD_SERVER --auth-token $ARGOCD_AUTH_TOKEN
        argocd app sync simple-web-app --namespace dev
        argocd app wait simple-web-app --timeout 600s

      env:
        ARGOCD_SERVER: your-argocd-server
        ARGOCD_AUTH_TOKEN: your-argocd-auth-token


