name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t dpentim78/simple-web-app:${{ github.sha }} .
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push dpentim78/simple-web-app:${{ github.sha }}

    - name: Update Helm chart and deploy
      run: |
        sed -i 's|image: dpentim78/simple-web-app:.*|image: dpentim78/simple-web-app:${{ github.sha }}|' helm/simple-web-app/values.yaml
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add helm/simple-web-app/values.yaml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push

        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        argocd login ${{ secrets.ARGOCD_SERVER }} --auth-token ${{ secrets.ARGOCD_AUTH_TOKEN }}
        argocd app sync simple-web-app --namespace dev
        argocd app wait simple-web-app --timeout 600s

